version: '3.8'

services:
  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    restart: unless-stopped

  notifications-service:
    build: ./notifications
    ports:
      - "4000:4000"
    restart: unless-stopped
  
  invoices-service:
    build: ./invoices
    ports:
      - "3003:3003"
    restart: unless-stopped  