version: '3.8'

services:
  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    restart: unless-stopped

  verification-service:
    build: ./verification-service
    ports:
      - "3002:3002"
    volumes:
      - ./verification-service/uploads:/app/uploads
    restart: unless-stopped
